* [[https://devcenter.heroku.com/]]
** [[https://devcenter.heroku.com/articles/quickstart][Getting started]]
   1. [ ] [[https://devcenter.heroku.com/articles/quickstart#step-1-sign-up][Sign up]]
   2. [ ] [[https://devcenter.heroku.com/articles/quickstart#step-2-install-the-heroku-toolbelt][Install the Heroku Toolbelt]]
   3. [ ] [[https://devcenter.heroku.com/articles/quickstart#step-3-login][Login]]
   4. [ ] [[https://devcenter.heroku.com/articles/quickstart#step-4-deploy-an-application][Deploy an application]]
* Rails 4 to Heroku Step by Step ( see https://devcenter.heroku.com/articles/getting-started-with-rails4 )
  1. [ ] [[https://devcenter.heroku.com/articles/getting-started-with-rails4#write-your-app][Write the application]]
     1. [ ] Create a new Rails application using postgresql
	    #+begin_src sh
	      rails new app_name --database postgresql
	    #+end_src
     2. [ ] Change into the application directory
     3. [ ] Edit Gemfile ( see https://devcenter.heroku.com/articles/rails4 )
        #+BEGIN_SRC ruby
          # 2014-07-11
          gem 'rails_12factor', group: :production
        #+END_SRC
     4. [ ] Re-install dependencies to generate a new Gemfile.lock
        #+BEGIN_SRC sh
          bundle install
        #+END_SRC
  2. [ ] Set up the Postgresql database
     1. [ ] template: template0
     2. [ ] rake db:create
  3. [ ] Test Rails application locally
     1. [ ] Start the Rails server
	#+BEGIN_SRC sh
          rails server
        #+END_SRC
     2. [ ] view localhost:3000 with web browser
  4. [ ] Store the application in Git
     #+BEGIN_SRC sh
       git init
       git add .
       git commit -m "init"
     #+END_SRC
  5. [ ] Enable a JavaScript runtime in Gemfile
     #+BEGIN_SRC ruby
       gem 'therubyracer',  platforms: :ruby
     #+END_SRC
  6. [ ] Create a “home” controller and “home/index”, "home/about", "home/contact" pages
     #+BEGIN_SRC sh :tangle bin/generate-controller-home.sh :shebang #!/bin/sh
       rails generate controller home index about contact --skip-stylesheets
     #+END_SRC
     Note the use of '--skip-stylesheets' since we will use Twitter Bootstrap's stylesheets
  7. [ ] Set the default route to home/index in [[file:config/routes.rb][config/routes.rb]]
     
     Open [[file:config/routes.rb][config/routes.rb]]  with your text editor. You will see the following
     commented line near the top of the file:
     #+BEGIN_SRC ruby
       # root 'welcome#index'
     #+END_SRC
     
     Let's uncomment and change the application root view:

     #+BEGIN_SRC ruby
       root "home#index"
     #+END_SRC
     
     Now, Rails will direct vistors to the application to home/index. We are
     ready to start the Rails application and incorporate Twitter Bootstrap's
     stylesheets and JavaScript scripts.
  8. [/] Deploy the application to Heroku
     1. [ ] Create the application on Heroku
        #+BEGIN_SRC heroku
          heroku create
          # http://murmuring-bastion-5947.herokuapp.com/ | git@heroku.com:murmuring-bastion-5947.git
        #+END_SRC
	Creating mighty-badlands-8255... done, stack is cedar
	http://mighty-badlands-8255.herokuapp.com/ | git@heroku.com:mighty-badlands-8255.git
	Git remote heroku added
     2. [ ] Deploy the code
        #+BEGIN_SRC sh
          git push heroku master
        #+END_SRC
  9. [ ] Visit the application
  10. [ ] View the logs
      #+BEGIN_SRC sh
	heroku logs
      #+END_SRC
* ( Optional ) Delete the application and Postgresql database
  1. [ ] Delete the Heroku application
     #+BEGIN_SRC sh
       heroku apps:destroy --app nameless-hollows-6930       
     #+END_SRC
  2. [ ] Delete the Postgresql databases
     1. [ ] Become postgres user
	#+BEGIN_SRC sh
          sudo su - postgres
        #+END_SRC
     2. [ ] Open a PostgreSQL interactive terminal
	#+BEGIN_SRC sh
	  psql
	#+END_SRC
     3. [ ] List databases
	Type "\l"
   	#+BEGIN_SRC sh
	  postgres=# \l
	#+END_SRC
     4. [ ] drop databases
	#+BEGIN_SRC sql
	   drop database app_name_development;
	   drop database app_name_test;
	#+END_SRC
* [/] https://devcenter.heroku.com/articles/custom-domains
  1. [ ] 
     #+BEGIN_SRC sh
       heroku domains:add www.example.com
       # Adding www.example.com to example... done
     #+END_SRC
  2. [ ] CNAME (Alias)
     | HOST NAME  | IP ADDRESS/URL                   | RECORD TYPE   |
     |------------+----------------------------------+---------------|
     | weightloss | warm-citadel-7982.herokuapp.com. | CNAME (Alias) |
  
